### ISSUE TITLE
ValueError in concatenation of getPlayerStats(playerlinks)

### ISSUE THREAD

**Issue by dalesmidkiff** [msjoelin/eliteprospect_scraper#1]
I received the following error running the sample workbook. 
ValueError: No objects to concatenate.

![Concat Error](https://user-images.githubusercontent.com/88245362/178777242-3043703a-fa80-4786-930a-799940f08c2b.JPG)

**Comment by msjoelin** [comment]
Hi,
did you get it to work?
Have not updated the package for a while, and I know that eliteprospect has
done some changes on the page

**Comment by dalesmidkiff** [comment]
Hi, yes. It just needed the table name changed. The location is reproduced below.
------------------------------------------------------------------------------------------

def getPlayerStats(playerlinks): 
    """
    Takes series of playerlinks to eliteprospect-profiles, 
    Return dataframe with stats by player and season
    """    
    
    # Name of table to get data from
    tablename = "table table-condensed table-sortable player-stats skater-stats highlight-stats"

**Comment by msjoelin** [comment]
Nice :)
